### ISSUE TITLE
edit and reply saved request. 

### ISSUE THREAD

**Issue by unknowen700** [ProxymanApp/proxyman-windows-linux#354]
hi 
first your app is really greater app i found on the web 

## Description
edit and reply saved request  add the repeated request to saved list 
when you edit old request from saved list ,  the program  add new one  to saved  list 
this lead to large of clone saved and user lose the original request. 
can you pleas edit this to make new request show only at main requests not saved automatically 

## Steps to Reproduce
1.send any request
2.click on save this request.
3.restart proxyman 
4.edit and repeat saved request  
5. you will find every request you made is saved automaticity 

- Windows

**Comment by kics223w1** [comment]
Hi @unknowen700 
This behavior is the same as Proxyman on macOS, but I'll ask the founder about this and make the changes in the next release.

**Comment by NghiaTranUIT** [comment]
@unknowen700 it's our intention. Let's say that we're selecting the Saved Folder, and we repeat one of any requests:
- If the new request doesn't append into the Saved folder -> Users have no idea where the repeated requests are (In fact, they have to select the All Domains to see it) -> Get confusing -> Bad UX
- If new repeated request appends into the Saved Folder, but it doesn't save it -> It's inconsistent because these requests are in the same place with other saved requests but not it's saved 
- ...

=> Therefore, I decided to keep this way. Repeat a request in the Saved Folder, also save it too 👍

**Comment by unknowen700** [comment]
i can handle this for me i save the request at third part program to test 
but i just want you to know this for other users this  will  help them 

 i think you need to make collection for saved section 
if user save domain or endpoint  A and also save request at B then user decide to test A request and change things and keep send the request this ended with me for more then 25 new request  . at saved dialog  and i don't need them because i only save what's important for me   also i lost the original request and also i lost the one who has result i want to save to work on later  

now  saved request A  And B has large log and trays shuffle together

**Comment by unknowen700** [comment]
![exa](https://github.com/ProxymanApp/proxyman-windows-linux/assets/86002517/4696a90e-8c81-47ed-a49f-58d36aad9484)

this what I'm try to say i ended with 600 request without know what the one was the original 
even i can comment the original one if i keep testing like this way i will have more larger req list 
and there was saved request for A and B and c   now every thing at same log

**Comment by NghiaTranUIT** [comment]
Thanks @unknowen700 for your input. I will consider to add this feature if there more users have the same problem 👍

**Comment by unknowen700** [comment]
thank you and i hope you have greate day
